{{- if .Values.ingress.enabled -}}
{{- $fullName := include "demo-anti-spoofer.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hosts := list "localhost" (printf "%s-kong-proxy" .Release.Name) ( .Values.global.external_host | default (printf "%s.eng.smartdigits.io" .Release.Name)) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "demo-anti-spoofer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default (printf "%s-kong" .Release.Name) }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $index, $host := $hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
